services:
  - type: worker
    name: telegram-sentiment-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1" 